#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  information:
    docker:
      - image: circleci/node:10.10.0
    resource_class: small
    steps:
      - run:
          name: Check versions
          command: |
            npm -v
            yarn -v

  showFiles:
    docker:
      - image: circleci/node:10.10.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'

  unitTesting:
    parallelism: 4
    docker:
      - image: circleci/node:10.10.0
    resource_class: small
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'

      - run:
          name: Unit test
          command: npm run test:ci

      - store_test_results:
          path: coverage

      - store_artifacts:
          path: coverage
          prefix: coverage

  Hello-World:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Hello World
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  I-Have-Code:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
  Run-With-Node:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - run:
          name: Running In A Container With Node
          command: |
            node -v
  Now-Complete:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'Do work once the approval has completed'

workflows:
 version: 2
 Example_Workflow:
   jobs:
     - Hello-World
     - information
     - showFiles
     - unitTesting
     - I-Have-Code:
         requires:
           - Hello-World
           - information
           - unitTesting
     - Run-With-Node:
         requires:
           - Hello-World
           - information
           - unitTesting
     - Now-Complete:
         requires:
           - Run-With-Node
           - I-Have-Code
